site_name: Constructra Documentation
site_description: A comprehensive guide to Constructra, the factory-building Minecraft mod.
site_url: https://docs.tiazzz.me/Constructra
theme:
  name: material
  palette:
      - scheme: slate
        toggle:
          icon: material/weather-sunny
          name: Dark mode
        primary: deep purple
        accent: pink
      - scheme: default
        toggle:
          icon: material/weather-night
          name: Light mode
        primary: deep purple
        accent: pink
  logo: assets/Main_Transparent.png
  features:
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - content.code.copy
    - content.code.select
nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - User Guide:
    - Getting Started:
      - Prerequisites: users/getting-started.md
      - Gameplay: users/getting-started-game.md
  - Playground: playground.md
plugins:
  - search
  - blog:
      draft_if_future_date: true
  - tags
  - rss:
      match_path: "blog/posts/.*"
      pretty_print: true
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
copyright: Copyright &copy; 2025 Tywrap Studios; Released under the MIT License